version: "3"
services:
  vertex-lite:
    container_name: vertex-lite
    image: kuanghom/vertex:simple
    restart: always
    network_mode: bridge
    volumes:
      - ./vertex-lite-data:/vertex
    environment:
      - PORT=3000
    ports:
      - 3000:3000
